project:
  type: website
  output-dir: _site
  execute-dir: project

resources:
  - assets/
  - _meta/theme/*.css

website:
  title: "Technical Library"
  site-url: "https://library.land.copernicus.eu"
  page-navigation: true
  back-to-top-navigation: true
  bread-crumbs: true
  search:
    type: textbox
  navbar:
    background: "#a0b128"
    foreground: "#ffffff"
  page-footer:
    left: |
      2025 EEA. All rights reserved.

language:
  search-text-placeholder: Search ...

format:
  html:
    output-dir: _site # Moves rendered files outside DOCS/
    include-before-body: _meta/includes/main-logos.html
    page-layout: full
    css: _meta/theme/main.css
